# Javascript Node CircleCI 2.0 configuration file

version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:9.2.1
    working_directory: ~/elephante-api

    steps:
      echo "Beginning to deploy"
      - checkout
      - run: npm install
