version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.26
    restart: always
    ports:
    - "5432:5432"
    environment:
      PRISMA_CONFIG: |
        port: 5432
        databases:
          default:
            connector: postgres
            migrations: true
            host: postgres
            port: 5432
            user: postgres
            password: psql_password
            migrations: true
  postgres:
    image: postgres:10.5
    restart: always
    container_name: treelab_psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql_password
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:

