version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.2.1
    working_directory: ~/elephante-api
    steps:
      - checkout
      - run: echo "hello world test again"
      - run: 
          command: echo ${TESTING_VAR}
      - deploy:
          name: deploy to AWS EC2
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              echo "this is is branch master"
            else
              echo "this is NOT branch! ${CIRCLE_BRANCH}"
            fi
workflows:
  version: 2
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/