# More details: https://gist.github.com/ryansimms/808214137d219be649e010a07af44bad
version: 2
jobs:
  build:
    working_directory: ~/treelab-api
    branches:
      only:
          - circle-ci-moya
    docker:
      - image: node:10.15.0
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing NPM dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
              apt-get -y -qq update
              apt-get -y install python-pip python-dev build-essential
              pip install awsebcli --upgrade
      - deploy:
          name: Starting deployment
          command: eb deploy TreelabApi-env
      # - run: # run tests
      #     name: test
      #     command: npm test
      # - run: # run coverage report
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts: # special step to save test results as as artifact
      #     # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      #     path: coverage
      #     prefix: coverage
      # - store_test_results: for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      #     path: test-results.xml
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples